export type DispatchRoute = {
  mount: string;
  exportName: string;
  /** Import specifier relative to the generated dispatch file. */
  importPath: string;
  id: string;
  dynamic: boolean;
  bindings: readonly string[];
};

const GENERATED_HEADER = `// Generated by rinka — do not edit by hand.
// @ts-nocheck -- generated by rinka codegen; edits belong in packages/rinka/src/vite/*
/* oxlint-disable -- generated by rinka codegen; do not lint the codegen output */`;

function formatBindings(bindings: readonly string[]): string {
  return bindings.length === 0 ? "[]" : `[${bindings.map((b) => JSON.stringify(b)).join(", ")}]`;
}

/**
 * Emits `registerDispatch(app)`, which wires every route onto the host-owned
 * Hono app in registration order: inline routes are mounted directly; dynamic
 * routes are wrapped with `dynamic()` so a matching request is delegated to its
 * Worker isolate (and the host router still owns matching, so the gateway keeps
 * whatever router it chose).
 */
export function formatDispatchSource(routes: DispatchRoute[]): string {
  const imports = routes.map(
    (route, i) =>
      `import { ${route.exportName} as r${i} } from ${JSON.stringify(route.importPath)};`,
  );
  const registrations = routes.map((route, i) => {
    if (route.dynamic) {
      const options = `{ id: ${JSON.stringify(route.id)}, bindings: ${formatBindings(route.bindings)} }`;
      return `  app.route(${JSON.stringify(route.mount)}, dynamic(r${i}, ${options}));`;
    }
    return `  app.route(${JSON.stringify(route.mount)}, r${i});`;
  });

  return `${GENERATED_HEADER}
import type { Hono } from "hono";
import { dynamic } from "rinka";
// Side-effect: registers the dynamic route manifest and host-embedded modules.
import "./dynamic-manifest";
${imports.join("\n")}

export function registerDispatch(app: Hono<any, any, any>): void {
${registrations.join("\n")}
}
`;
}
