export type AppTypeRoute = {
  mount: string;
  exportName: string;
  /** Import specifier relative to the generated app-type file. */
  importPath: string;
};

const GENERATED_HEADER = `// Generated by rinka — do not edit by hand.
// @ts-nocheck -- generated by rinka codegen; edits belong in packages/rinka/src/vite/*
/* oxlint-disable -- generated by rinka codegen; do not lint the codegen output */`;

/**
 * Emits the type-only route aggregator. Composing every route with `.route()`
 * and exporting `typeof app` gives one `AppType` for Hono RPC — decoupled from
 * the runtime gateway. Consumed via `import type`, so it is erased and never
 * bundled, even though it imports the (possibly dynamic) route modules.
 */
export function formatAppTypeSource(routes: AppTypeRoute[]): string {
  const imports = routes.map(
    (route, i) =>
      `import { ${route.exportName} as r${i} } from ${JSON.stringify(route.importPath)};`,
  );
  const chain = routes.map((route, i) => `  .route(${JSON.stringify(route.mount)}, r${i})`);
  const appExpr = chain.length === 0 ? "new Hono()" : `new Hono()\n${chain.join("\n")}`;

  return `${GENERATED_HEADER}
import { Hono } from "hono";
${imports.join("\n")}

const app = ${appExpr};

export type AppType = typeof app;
`;
}
