import { describe, expect, it } from "vite-plus/test";
import { formatRouterInitSource } from "./format-router-init";

describe("formatRouterInitSource", () => {
  it("embeds /v1/health in PreparedRegExpRouter params", () => {
    const source = formatRouterInitSource(["/v1/health", "/v1/events/ws"]);
    expect(source).toContain('"/v1/health"');
    expect(source).toContain("routerParams");
    expect(source).toContain("@ts-nocheck -- generated by hibana codegen");
    expect(source).toContain("oxlint-disable -- generated by hibana codegen");
  });
});
