import type { DynamicRouteBinding } from "../binding-policy";
import type { ScannedDynamicRoute } from "./scan-dynamic-routes";

export type ManifestRoute = Pick<ScannedDynamicRoute, "id"> & {
  resolvedBindings: readonly DynamicRouteBinding[];
};

const IDENTIFIER_KEY = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function formatKey(id: string): string {
  return IDENTIFIER_KEY.test(id) ? id : JSON.stringify(id);
}

function formatValue(value: unknown): string {
  if (Array.isArray(value)) {
    return value.length === 0 ? "[]" : `[${value.map(formatValue).join(", ")}]`;
  }
  if (typeof value === "object" && value !== null) {
    const fields = Object.entries(value).map(
      ([key, entry]) => `${formatKey(key)}: ${formatValue(entry)}`,
    );
    return fields.length === 0 ? "{}" : `{ ${fields.join(", ")} }`;
  }
  return JSON.stringify(value);
}

function formatBinding(binding: DynamicRouteBinding): string {
  return formatValue(binding);
}

// The emitted source must be oxfmt-stable (100-col width, trailing commas,
// unquoted identifier keys) so codegen and `vp fmt` don't fight over the file.
function formatBindings(bindings: readonly DynamicRouteBinding[]): string {
  if (bindings.length === 0) return "[]";
  const singleLine = `[${bindings.map(formatBinding).join(", ")}]`;
  if (`    bindings: ${singleLine},`.length <= 100) return singleLine;
  return `[\n${bindings.map((binding) => `      ${formatBinding(binding)},`).join("\n")}\n    ]`;
}

export function formatDynamicManifestSource(routes: ManifestRoute[]): string {
  const entries = routes.map((route) => {
    return `  ${formatKey(route.id)}: {
    bindings: ${formatBindings(route.resolvedBindings)},
  },`;
  });
  const manifestBody = entries.length === 0 ? "{}" : `{\n${entries.join("\n")}\n}`;

  return `// Generated by rinka — do not edit by hand.
// @ts-nocheck -- generated by rinka codegen; edits belong in packages/rinka/src/vite/*
/* oxlint-disable -- generated by rinka codegen; do not lint the codegen output */
import { registerDynamicRouteManifest, type DynamicRouteManifest } from "rinka";
// Side-effect import: registers the host-embedded dynamic Worker module code.
import "./dynamic-modules";

export const dynamicRouteManifest: DynamicRouteManifest = ${manifestBody};
registerDynamicRouteManifest(dynamicRouteManifest);
`;
}

/**
 * Emits the host-embedded module registry: each dynamic route's bundled Worker
 * code as a string constant, registered so the host can hand it to Worker
 * Loader without an asset fetch. Generated (do-not-edit) and imported by the
 * manifest.
 */
export function formatDynamicModulesSource(modules: Record<string, string>): string {
  const ids = Object.keys(modules);
  const entries = ids.map((id) => `  ${formatKey(id)}: ${JSON.stringify(modules[id])},`);
  const body = entries.length === 0 ? "{}" : `{\n${entries.join("\n")}\n}`;

  return `// Generated by rinka — do not edit by hand.
// @ts-nocheck -- generated by rinka codegen; edits belong in packages/rinka/src/vite/*
/* oxlint-disable -- generated by rinka codegen; do not lint the codegen output */
import { registerDynamicModules } from "rinka";

export const dynamicModules: Record<string, string> = ${body};
registerDynamicModules(dynamicModules);
`;
}
