import { buildInitParams, serializeInitParams } from "hono/router/reg-exp-router";

export function formatRouterInitSource(paths: string[]): string {
  const uniquePaths = Array.from(new Set(paths));
  const serialized = serializeInitParams(buildInitParams({ paths: uniquePaths }));
  return `// Generated by hibana — do not edit by hand.
// @ts-nocheck -- generated by hibana codegen; edits belong in packages/hibana/src/vite/*
/* oxlint-disable -- generated by hibana codegen; do not lint the codegen output */
import type { PreparedRegExpRouter } from "hono/router/reg-exp-router";

// prettier-ignore
export const routerParams: ConstructorParameters<typeof PreparedRegExpRouter> = ${serialized};
`;
}
